## Basic data cleaning for each dataset

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("../raw/listed/CRMLSListing202402.csv")
display(df.head())
display(df.info())
display(df.shape)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1000.0,421654881,luann.hall@sbcglobal.net,NaN,NaN,Lu Ann,Hall,33.138645,-117.180289,823 Grand Avenue 203,...,NaN,NaN,NaN,NaN,92078,NaN,0.0,60112.8,NaN,823 Grand Avenue 203
1,799999.0,1075011484,Christina.sdsu12@gmail.com,NaN,NaN,Christina,Diab,NaN,NaN,10924 Via Banco,...,NaN,False,1.0,NaN,92126,NaN,195.0,720740.0,NaN,10924 Via Banco
2,820000.0,1075000634,ethan@c2realty.com,NaN,NaN,Ethan,Kolb,37.340056,-120.434070,2918 Dunn Road,...,1.0,False,0.0,Merced City,95340,NaN,0.0,95528.0,NaN,2918 Dunn Road
3,1300000.0,1074997455,jportillo@kw.com,NaN,NaN,Jason,Portillo,34.577993,-118.154162,1 Mile W Tierra Subida Q,...,NaN,False,NaN,NaN,93550,NaN,0.0,1744142.4,NaN,1 Mile W Tierra Subida Q
4,489999.0,1074990034,corey@murphyhousing.com,NaN,NaN,Corey,Murphy,33.141744,-117.091877,1421 N Broadway E,...,0.0,NaN,1.0,Escondido Union,92026,NaN,561.0,341510.4,NaN,1421 N Broadway E

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27447 entries, 0 to 27446
Data columns (total 84 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   OriginalListPrice             27328 non-null  float64
 1   ListingKey                    27447 non-null  int64
 2   ListAgentEmail                27411 non-null  object
 3   CloseDate                     17387 non-null  object
 4   ClosePrice                    17141 non-null  float64
 5   ListAgentFirstName            27266 non-null  object
 6   ListAgentLastName             27445 non-null  object
 7   Latitude                      21814 non-null  float64
 8   Longitude                     21859 non-null  float64
 9   UnparsedAddress               27369 non-null  object
 10  PropertyType                  27447 non-null  object
 11  LivingArea                    23669 non-null  float64
 12  ListPrice                     27376 non-null  float64
 13  DaysOnMarket                  27447 non-null  int64
 14  ListOfficeName                27447 non-null  object
 15  BuyerOfficeName               17042 non-null  object
 16  CoListOfficeName              5367 non-null   object
 17  ListAgentFullName             27445 non-null  object
 18  CoListAgentFirstName          5321 non-null   object
 19  CoListAgentLastName           5333 non-null   object
 20  BuyerAgentMlsId               17277 non-null  object
 21  BuyerAgentFirstName           17200 non-null  object
 22  BuyerAgentLastName            17300 non-null  object
 23  FireplacesTotal               0 non-null      float64
 24  AssociationFeeFrequency       8041 non-null   object
 25  AboveGradeFinishedArea        0 non-null      float64
 26  ListingKeyNumeric             27447 non-null  int64
 27  MLSAreaMajor                  24459 non-null  object
 28  TaxAnnualAmount               232 non-null    float64
 29  CountyOrParish                27446 non-null  object
 30  PropertyType.1                27447 non-null  object
 31  MlsStatus                     27447 non-null  object
 32  ElementarySchool              2786 non-null   object
 33  ListAgentFirstName.1          27266 non-null  object
 34  AttachedGarageYN              18242 non-null  object
 35  ParkingTotal                  25502 non-null  float64
 36  BuilderName                   1050 non-null   object
 37  PropertySubType               23807 non-null  object
 38  LotSizeAcres                  24682 non-null  float64
 39  SubdivisionName               9263 non-null   object
 40  BuyerOfficeAOR                16704 non-null  object
 41  YearBuilt                     24967 non-null  float64
 42  DaysOnMarket.1                27447 non-null  int64
 43  BuyerAgencyCompensationType   27404 non-null  object
 44  StreetNumberNumeric           27304 non-null  float64
 45  LivingArea.1                  23669 non-null  float64
 46  ListingId                     27447 non-null  object
 47  BathroomsTotalInteger         24913 non-null  float64
 48  City                          27412 non-null  object
 49  BuyerAgencyCompensation       27415 non-null  float64
 50  TaxYear                       33 non-null     float64
 51  BuildingAreaTotal             4119 non-null   float64
 52  BedroomsTotal                 23772 non-null  float64
 53  ContractStatusChangeDate      27334 non-null  object
 54  Longitude.1                   21859 non-null  float64
 55  ElementarySchoolDistrict      0 non-null      float64
 56  CoBuyerAgentFirstName         1441 non-null   object
 57  PurchaseContractDate          19608 non-null  object
 58  ListingContractDate           27447 non-null  object
 59  BelowGradeFinishedArea        87 non-null     float64
 60  BusinessType                  223 non-null    object
 61  Latitude.1                    21814 non-null  float64
 62  ListPrice.1                   27376 non-null  float64
 63  StateOrProvince               27446 non-null  object
 64  CoveredSpaces                 0 non-null      float64
 65  MiddleOrJuniorSchool          2852 non-null   object
 66  FireplaceYN                   23136 non-null  object
 67  Stories                       19915 non-null  float64
 68  HighSchool                    3635 non-null   object
 69  Levels                        21642 non-null  object
 70  ListAgentLastName.1           27445 non-null  object
 71  CloseDate.1                   17387 non-null  object
 72  LotSizeDimensions             1424 non-null   object
 73  LotSizeArea                   24794 non-null  float64
 74  MainLevelBedrooms             12702 non-null  float64
 75  NewConstructionYN             23586 non-null  object
 76  GarageSpaces                  22163 non-null  float64
 77  HighSchoolDistrict            16697 non-null  object
 78  PostalCode                    27441 non-null  object
 79  BuyerOfficeName.1             17042 non-null  object
 80  AssociationFee                18835 non-null  float64
 81  LotSizeSquareFeet             24754 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 83  UnparsedAddress.1             27369 non-null  object
dtypes: float64(32), int64(4), object(48)
memory usage: 17.6+ MB

None

(27447, 84)

In [10]:
for col in df.columns:
    if col.endswith('.1'):
        base_col = col[:-2]
        if base_col in df.columns:
            print(base_col, df[base_col].equals(df[col]))

PropertyType True
ListAgentFirstName True
DaysOnMarket True
LivingArea True
Longitude True
Latitude True
ListPrice True
ListAgentLastName True
CloseDate True
BuyerOfficeName True
UnparsedAddress True

In [7]:
df[df['ListPrice'] != df['ListPrice.1']][['ListPrice', 'ListPrice.1']]

       ListPrice  ListPrice.1
126          NaN          NaN
461          NaN          NaN
547          NaN          NaN
930          NaN          NaN
932          NaN          NaN
...          ...          ...
25669        NaN          NaN
25696        NaN          NaN
25858        NaN          NaN
26020        NaN          NaN
26727        NaN          NaN

[71 rows x 2 columns]