## Deep cleaning of merged dataset

In [1]:
import pandas as pd

In [3]:
report = pd.read_csv("../../processed/listed/cleaning_report.csv")
report

,file,rows_raw,cols_raw,source_month,duplicate_pairs_found,duplicate_pairs_identical,duplicate_pairs_different,dropped_duplicate_cols,kept_duplicate_cols,rows_clean,cols_clean
0,CRMLSListing202401.csv,27454,84,2024-01,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],27454,75
1,CRMLSListing202402.csv,27447,84,2024-02,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],27447,75
2,CRMLSListing202403.csv,32282,84,2024-03,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],32282,75
3,CRMLSListing202404.csv,36503,84,2024-04,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],36503,75
4,CRMLSListing202405.csv,38796,82,2024-05,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],38796,73
5,CRMLSListing202406.csv,35893,82,2024-06,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],35893,73
6,CRMLSListing202407.csv,36340,82,2024-07,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],36340,73
7,CRMLSListing202408.csv,35305,82,2024-08,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],35305,73
8,CRMLSListing202409.csv,34625,82,2024-09,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],34625,73
9,CRMLSListing202410.csv,34730,82,2024-10,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],34730,73
10,CRMLSListing202411.csv,25128,82,2024-11,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],25128,73
11,CRMLSListing202412.csv,19417,82,2024-12,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],19417,73
12,CRMLSListing202501.csv,37469,82,2025-01,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],37469,73
13,CRMLSListing202502.csv,33983,82,2025-02,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],33983,73
14,CRMLSListing202503.csv,38492,82,2025-03,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],38492,73
15,CRMLSListing202504.csv,40187,82,2025-04,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],40187,73
16,CRMLSListing202505.csv,40271,82,2025-05,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],40271,73
17,CRMLSListing202506.csv,26399,82,2025-06,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],26399,73
18,CRMLSListing202507.csv,27345,82,2025-07,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],27345,73
19,CRMLSListing202508.csv,25210,82,2025-08,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],25210,73
20,CRMLSListing202509.csv,26923,82,2025-09,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],26923,73
21,CRMLSListing202510.csv,27586,82,2025-10,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],27586,73
22,CRMLSListing202511.csv,20677,82,2025-11,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],20677,73
23,CRMLSListing202512.csv,18773,82,2025-12,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],18773,73
24,CRMLSListing202601.csv,35302,82,2026-01,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],35302,73
25,CRMLSListing202602.csv,31785,81,2026-02,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],31785,72
26,CRMLSListing202603.csv,39102,81,2026-03,11,11,0,"['PropertyType.1', 'ListAgentFirstName.1', 'Da...",[],39102,72

### 1. Check different columns among raw datasets

In [7]:
df_base = pd.read_csv('../../raw/listed/CRMLSListing202401.csv')
base_cols = set(df_base.columns)

In [9]:
from pathlib import Path

folder = Path(r"../../raw/listed")
files = sorted(folder.glob("*.csv"))

col_sets = {}

for f in files:
    df = pd.read_csv(f, nrows=5)   # 只读前几行也行，主要是拿列名
    col_sets[f.name] = set(df.columns)

print("baseline:", "CRMLSListing202401.csv")

for fname, cols in col_sets.items():
    missing = base_cols - cols
    extra = cols - base_cols
    print(f"\n{fname}")
    print("missing:", sorted(missing))
    print("extra:", sorted(extra))

baseline: CRMLSListing202401.csv

CRMLSListing202401.csv
missing: []
extra: []

CRMLSListing202402.csv
missing: []
extra: []

CRMLSListing202403.csv
missing: []
extra: []

CRMLSListing202404.csv
missing: []
extra: []

CRMLSListing202405.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202406.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202407.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202408.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202409.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202410.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202411.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202412.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202501.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202502.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202503.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202504.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202505.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202506.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202507.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202508.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202509.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202510.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202511.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202512.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202601.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType']
extra: []

CRMLSListing202602.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType', 'ListAgentEmail']
extra: []

CRMLSListing202603.csv
missing: ['BuyerAgencyCompensation', 'BuyerAgencyCompensationType', 'ListAgentEmail']
extra: []

In [5]:
report["dropped_duplicate_cols"].value_counts()

dropped_duplicate_cols
['PropertyType.1', 'ListAgentFirstName.1', 'DaysOnMarket.1', 'LivingArea.1', 'Longitude.1', 'Latitude.1', 'ListPrice.1', 'ListAgentLastName.1', 'CloseDate.1', 'BuyerOfficeName.1', 'UnparsedAddress.1']    27
Name: count, dtype: int64

### 2. Deep cleaning

#### 2.1 Check duplicated rows of the merged dataset

In [25]:
df = pd.read_csv("../../processed/listed/merged_cleaned.csv")
display(df.head())
display(df.info())
display(df.shape)

/var/folders/bn/snz6hdrs7gbfh48m_qnfs_dr0000gn/T/ipykernel_93237/3999827961.py:1: DtypeWarning: Columns (2,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../processed/listed/merged_cleaned.csv")

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,source_file,source_month
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,0.0,NaN,NaN,CRMLSListing202401.csv,2024-01
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,0.0,NaN,NaN,CRMLSListing202401.csv,2024-01
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,2105.0,177861.0,NaN,CRMLSListing202401.csv,2024-01
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,254.0,5300.0,NaN,CRMLSListing202401.csv,2024-01
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,9404.0,NaN,CRMLSListing202401.csv,2024-01

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853424 entries, 0 to 853423
Data columns (total 75 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             850112 non-null  float64
 1   ListingKey                    853424 non-null  int64
 2   ListAgentEmail                780379 non-null  object
 3   CloseDate                     258598 non-null  object
 4   ClosePrice                    235978 non-null  float64
 5   ListAgentFirstName            848420 non-null  object
 6   ListAgentLastName             853348 non-null  object
 7   Latitude                      741494 non-null  float64
 8   Longitude                     742198 non-null  float64
 9   UnparsedAddress               851278 non-null  object
 10  PropertyType                  853424 non-null  object
 11  LivingArea                    746964 non-null  float64
 12  ListPrice                     851290 non-null  float64
 13  DaysOnMarket                  853424 non-null  int64
 14  ListOfficeName                853424 non-null  object
 15  BuyerOfficeName               248258 non-null  object
 16  CoListOfficeName              170951 non-null  object
 17  ListAgentFullName             853196 non-null  object
 18  CoListAgentFirstName          170321 non-null  object
 19  CoListAgentLastName           170809 non-null  object
 20  BuyerAgentMlsId               249869 non-null  object
 21  BuyerAgentFirstName           249704 non-null  object
 22  BuyerAgentLastName            250625 non-null  object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       246289 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             853424 non-null  int64
 27  MLSAreaMajor                  757090 non-null  object
 28  TaxAnnualAmount               6087 non-null    float64
 29  CountyOrParish                853423 non-null  object
 30  MlsStatus                     853424 non-null  object
 31  ElementarySchool              79276 non-null   object
 32  AttachedGarageYN              562486 non-null  object
 33  ParkingTotal                  801060 non-null  float64
 34  BuilderName                   29295 non-null   object
 35  PropertySubType               749282 non-null  object
 36  LotSizeAcres                  771918 non-null  float64
 37  SubdivisionName               285041 non-null  object
 38  BuyerOfficeAOR                236219 non-null  object
 39  YearBuilt                     783962 non-null  float64
 40  BuyerAgencyCompensationType   123538 non-null  object
 41  StreetNumberNumeric           849664 non-null  float64
 42  ListingId                     853424 non-null  object
 43  BathroomsTotalInteger         783471 non-null  float64
 44  City                          852463 non-null  object
 45  BuyerAgencyCompensation       123519 non-null  float64
 46  TaxYear                       868 non-null     float64
 47  BuildingAreaTotal             136798 non-null  float64
 48  BedroomsTotal                 750350 non-null  float64
 49  ContractStatusChangeDate      846553 non-null  object
 50  ElementarySchoolDistrict      0 non-null       float64
 51  CoBuyerAgentFirstName         19959 non-null   object
 52  PurchaseContractDate          370310 non-null  object
 53  ListingContractDate           853424 non-null  object
 54  BelowGradeFinishedArea        3423 non-null    float64
 55  BusinessType                  5979 non-null    object
 56  StateOrProvince               853357 non-null  object
 57  CoveredSpaces                 0 non-null       float64
 58  MiddleOrJuniorSchool          79373 non-null   object
 59  FireplaceYN                   730902 non-null  object
 60  Stories                       632206 non-null  float64
 61  HighSchool                    104332 non-null  object
 62  Levels                        689600 non-null  object
 63  LotSizeDimensions             48682 non-null   object
 64  LotSizeArea                   775699 non-null  float64
 65  MainLevelBedrooms             394914 non-null  float64
 66  NewConstructionYN             738710 non-null  object
 67  GarageSpaces                  691418 non-null  float64
 68  HighSchoolDistrict            514202 non-null  object
 69  PostalCode                    853216 non-null  object
 70  AssociationFee                577794 non-null  float64
 71  LotSizeSquareFeet             774621 non-null  float64
 72  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 73  source_file                   853424 non-null  object
 74  source_month                  853424 non-null  object
dtypes: float64(28), int64(3), object(44)
memory usage: 488.3+ MB

None

(853424, 75)

In [26]:
df.duplicated().sum()

0

In [27]:
df['ListingKey'].duplicated().sum()

122

In [ ]:
dup = df[df['ListingKey'].duplicated(keep=False)]

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,source_file,source_month
10734,360000.0,1058451843,luiscejarealtor@gmail.com,NaN,NaN,Luis,Ceja,32.139826,-116.891356,28 Calle Mirador 204,...,NaN,False,0.0,Call Listing Office,00000,130.00,NaN,NaN,CRMLSListing202401.csv,2024-01
12495,409000.0,1058408504,marierealtor4you@gmail.com,NaN,NaN,Marie,Arredondo,33.207200,-116.299900,3135 Club Circle East,...,1.0,NaN,2.0,Borrego Springs Unified,92004,0.00,34848.0,NaN,CRMLSListing202401.csv,2024-01
18260,150000.0,1055510600,thomas.gruss@exprealty.com,NaN,NaN,Thomas,Gruss,32.714843,-117.018651,Jamacha Road,...,NaN,NaN,NaN,NaN,91977,0.00,10454.4,NaN,CRMLSListing202401.csv,2024-01
27461,829000.0,1074974446,jaimeagent@gmail.com,NaN,NaN,Jaime,Mora,32.746462,-117.042366,7212 Waite Drive,...,NaN,NaN,2.0,La Mesa-Spring Valley,91941,0.00,6200.0,NaN,CRMLSListing202402.csv,2024-02
34140,749000.0,1061668014,bsully59@hotmail.com,NaN,NaN,Brian,Sullivan,33.152998,-117.288508,3480 Don Lorenzo Drive,...,2.0,NaN,0.0,Carlsbad Unified,92010,454.00,3528360.0,NaN,CRMLSListing202402.csv,2024-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814321,6000.0,1063377179,NaN,NaN,NaN,Jaime,Rook,33.162293,-117.266434,4717 Majorca Way,...,NaN,NaN,2.0,Oceanside Unified,92056,NaN,3519.0,NaN,CRMLSListing202602.csv,2026-02
853403,395000.0,1152169305,NaN,NaN,NaN,Bruce,Palizban,33.100054,-117.313562,7326 San Bartolo 220,...,NaN,False,3.0,NaN,92011,NaN,NaN,NaN,CRMLSListing202603.csv,2026-03
853412,665000.0,1151597485,NaN,NaN,NaN,Blake,Franklin,32.633228,-116.937675,1514 Crown Ln 2,...,NaN,False,2.0,NaN,91915,334.61,NaN,NaN,CRMLSListing202603.csv,2026-03
853413,3199.0,1151574398,NaN,NaN,NaN,Jay,Montenegro,32.781284,-117.170754,2036 Coolidge Street 81,...,NaN,NaN,0.0,NaN,92111,0.00,NaN,NaN,CRMLSListing202603.csv,2026-03
853418,475000.0,1150815309,NaN,NaN,NaN,Melissa,Sofia,32.801681,-117.237403,4600 lamont street 226,...,1.0,False,1.0,San Diego Unified,92109,802.00,428219.0,NaN,CRMLSListing202603.csv,2026-03

In [31]:
counts = df['ListingKey'].value_counts()
counts[counts > 1].head(20)

ListingKey
1076131624    5
1079186253    4
1104326441    4
1078833366    3
1076393700    3
1103394536    2
1063427862    2
1075673509    2
1153097672    2
1111787588    2
1151574398    2
1077480064    2
1112960460    2
1082108394    2
1104174596    2
1088242070    2
1076513598    2
1088166171    2
1089061633    2
1089116877    2
Name: count, dtype: int64

In [29]:
dup[['ListingKey', 'OriginalListPrice', 'ClosePrice', 'source_month']].sort_values('ListingKey')

        ListingKey  OriginalListPrice  ClosePrice source_month
493863  1016256058            40000.0         NaN      2025-03
87182   1016256058            40000.0         NaN      2024-03
653275  1024092497           125000.0         NaN      2025-08
304644  1024092497           125000.0         NaN      2024-09
728461  1041158198           429000.0         NaN      2025-11
...            ...                ...         ...          ...
853403  1152169305           395000.0         NaN      2026-03
798237  1153097672             9900.0         NaN      2026-02
747406  1153097672             9900.0         NaN      2026-01
797553  1153135127           949999.0         NaN      2026-02
747385  1153135127           949999.0         NaN      2026-01

[235 rows x 4 columns]

In [30]:
df.duplicated(subset=['ListingKey', 'source_month']).sum()

0

#### 2.2 Check missing values of the merged dataset

In [32]:
missing_ratio = df.isna().mean().sort_values(ascending=False)
missing_ratio.head(20)

FireplacesTotal                 1.000000
ElementarySchoolDistrict        1.000000
CoveredSpaces                   1.000000
MiddleOrJuniorSchoolDistrict    1.000000
AboveGradeFinishedArea          1.000000
TaxYear                         0.998983
BelowGradeFinishedArea          0.995989
BusinessType                    0.992994
TaxAnnualAmount                 0.992868
CoBuyerAgentFirstName           0.976613
BuilderName                     0.965674
LotSizeDimensions               0.942957
ElementarySchool                0.907108
MiddleOrJuniorSchool            0.906995
HighSchool                      0.877749
BuyerAgencyCompensation         0.855267
BuyerAgencyCompensationType     0.855244
BuildingAreaTotal               0.839707
CoListAgentFirstName            0.800426
CoListAgentLastName             0.799854
dtype: float64

In [ ]:
# Feature selection: Due to very high mssing ratio, dropped 'TaxYear', 'BelowGradeFinishedArea', 'BusinessType', 'TaxAnnualAmount'
drop_cols = [
    'FireplacesTotal',
    'ElementarySchoolDistrict',
    'CoveredSpaces',
    'MiddleOrJuniorSchoolDistrict',
    'AboveGradeFinishedArea',
    'TaxYear',
    'BelowGradeFinishedArea',
    'BusinessType',
    'TaxAnnualAmount'
]

df = df.drop(columns=drop_cols)

### 2.3 Check outliers of the merged dataset

In [35]:
numeric_cols = [
    'ListPrice',
    'LivingArea',
    'BedroomsTotal',
    'BathroomsTotalInteger',
    'LotSizeSquareFeet'
]

In [36]:
df[numeric_cols].describe()

,ListPrice,LivingArea,BedroomsTotal,BathroomsTotalInteger,LotSizeSquareFeet
count,8.512900e+05,7.469640e+05,750350.000000,783471.000000,7.746210e+05
mean,9.838219e+05,3.159972e+03,3.132622,2.498331,5.631946e+05
std,2.165003e+06,1.052048e+06,1.689136,3.034988,2.311756e+07
min,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00
25%,8.500000e+04,1.182000e+03,2.000000,2.000000,5.227000e+03
50%,6.350000e+05,1.602000e+03,3.000000,2.000000,7.500000e+03
75%,1.150000e+06,2.236000e+03,4.000000,3.000000,1.655700e+04
max,4.436503e+08,9.090909e+08,149.000000,2208.000000,7.638115e+09

In [41]:
df.sort_values('ListPrice', ascending=False).head(10)
df[['ListPrice']].sort_values('ListPrice').head(10)

        ListPrice
848524       0.00
307456       0.00
401203       0.00
506834       0.00
382000       0.00
661872       0.00
707725       0.00
447259       0.19
510665       0.20
840610       0.70

In [49]:
import numpy as np

df.loc[df['ListPrice'] <= 0, 'ListPrice'] = np.nan
df.loc[df['LivingArea'] <= 0, 'LivingArea'] = np.nan
df.loc[df['LotSizeSquareFeet'] <= 0, 'LotSizeSquareFeet'] = np.nan

In [50]:
df[numeric_cols].describe()

,ListPrice,LivingArea,BedroomsTotal,BathroomsTotalInteger,LotSizeSquareFeet
count,8.512830e+05,7.461240e+05,750350.000000,783471.000000,7.562100e+05
mean,9.838300e+05,3.163529e+03,3.132622,2.498331,5.769064e+05
std,2.165010e+06,1.052640e+06,1.689136,3.034988,2.339711e+07
min,1.900000e-01,1.000000e+00,0.000000,0.000000,1.000000e-02
25%,8.500000e+04,1.184000e+03,2.000000,2.000000,5.465000e+03
50%,6.350000e+05,1.603000e+03,3.000000,2.000000,7.562000e+03
75%,1.150000e+06,2.237000e+03,4.000000,3.000000,1.742400e+04
max,4.436503e+08,9.090909e+08,149.000000,2208.000000,7.638115e+09

In [53]:
df.to_csv("../..//processed/listed/listed_cleaned_v1.csv", index=False)